### ISSUE TITLE
No way to add custom properties to Input components

### ISSUE THREAD

**Issue by natearmagost** [react-materialize/react-materialize#112]
I'm trying to build an input element with custom properties. Something like this:

``` html
<div class="input-field col s12">
    <input class="uppercase" maxlength="2" id="code" type="text" />
    <label for="code">Code</label>
</div>
```

That's not going to work with:

``` html
<Input s={12} label="Code" maxLength="2" className="uppercase" />
```

Any properties meant for the input (maxlength, size, autocomplete, class/className) will be lost.

It would be nice to save those properties. Maybe by passing them down as an object? Something like this:

``` html
<Input s={12} label="code" inputProps={{maxLength: 5, className: 'uppercase'}} />
```

It looks like **placeholder** is the only property that makes it all the way to the input element right now. There quite a few valid HTML properties/attributes but I don't know if it makes sense to pinpoint all of the possibilities, and choose to either send the prop to the input vs. the label, etc...

``` html
<Input s={12} label="code" autocomplete="off" autofocus="on" width="20" min="1" etc. etc. etc. />
```

Any idea on this? Would you be open to a pull request?

**Comment by yanickrochon** [comment]
I had suggested to [filter the props](https://github.com/react-materialize/react-materialize/pull/103), and let all user-defined props pass-through... the PR is being "debated", but I still think that it would solve many problems and not restrict anyone. My initial solution had a home-made filter, but it seems that there's already a (new) project [that does this](https://www.npmjs.com/package/react-valid-props).

**Comment by alextrastero** [comment]
Hey @yanickrochon @natearmagost, thanks for pointing out these issues, luckily there's a better way than adding an external library to solve this. The props warning happens when you pass an unknown attribute to the node, ie `s={5}` to input. As mentioned here (https://facebook.github.io/react/docs/transferring-props.html#transferring-with-...-in-jsx), we should handle or separate the strange props differently.
So I'm destructuring s, m, l and passing the rest of the props (...other) to the input. That should stop these warnings and should let you pass any other native props down to the input.
Have a look here: https://github.com/react-materialize/react-materialize/pull/109

**Comment by natearmagost** [comment]
@alextrastero It doesn't look like className is passed to the input. In my case I could get around it by adding a class of "uppercase" to a wrapper element.

But there is a Materialize input class of "filled-in" that doesn't seem to make it to the input either. See the [Green filled in checkbox](https://react-materialize.github.io/forms.html) for reference.

```html
<Input name='group1' type='checkbox' value='green' label='Green' className='filled-in' checked='checked' />
```

**Comment by jhillhouse92** [comment]
@alextrastero any update on passing className?

**Comment by alextrastero** [comment]
cc/ @jhillhouse92 @natearmagost
