### ISSUE TITLE
Input does not support offset

### ISSUE THREAD

**Issue by yanickrochon** [react-materialize/react-materialize#160]
``` js
<Row>
  <Col s={12} m={8} l={6} offset="m2 l3">
    Some Title
  </Col>
  <Input s={12} m={8} l={6} offset="m2 l3" />
</Row>
```

Does not position the input field along with the column above, as `offset` is not passed down.

**Comment by alextrastero** [comment]
Hi @yanickrochon, ideally only Col's are children of Row's:
```js
<Row>
  <Col s={12} m={8} l={6} offset="m2 l3">
    Some Title
  </Col>
  <Col s={12} m={8} l={6} offset="m2 l3">
    <Input />
  </Col>
</Row>
```

**Comment by yanickrochon** [comment]
You are mistaken. You example produce this HTML :

```html
<div class="row">
  <div class="col s12 m8 l6 offset-m2 offset-l3">Some Title</div>
  <div class="col s12 m8 l6 offset-m2 offset-l3">
    <div class="col input-field">
      <input type="text" class="" id="input_2">
    </div>
  </div>
</div>
```

Can you see both `.col` elements? This is wrong markup for the semantic of Materialize design.

**Comment by loureirorg** [comment]
Here a quick and dirty workaround:
```css
.col > .input-field.col > label {
  left: 0;
}

.col > .input-field.col {
  width: 100%;
  padding: 0;
}
```
_**PS:** This CSS treats the symptom and not the causes and as result, the DOM will still be wrong (and I'm not sure about side-effects)._

**Comment by alextrastero** [comment]
PR's are welcome ;)

**Comment by nickvirden** [comment]
@alextrastero I've submitted a PR for this issue: https://github.com/react-materialize/react-materialize/pull/514

**Comment by alextrastero** [comment]
First of all thanks for the contribution!

Question though, since every component could benefit from having sizes props, we could either add them to all components (lots of work). Or remove them from Input and force users to actually use the cols for that, i.e.:

```jsx
<Col s={12} m={8} l={6} offset="m2 l3">
  <Input />
</Col>
```

Thoughts?

**Comment by alextrastero** [comment]
cc @nickvirden

**Comment by nickvirden** [comment]
@alextrastero That definitely seems like the better way to do things. I'll remove them in a commit to that same PR if that's alright. Or would you prefer I create a new PR?

**Comment by alextrastero** [comment]
It's a breaking change. The ability of adding Col classes to Input has been since the start. I would create another PR "remove sizes from Input" :)

**Comment by nickvirden** [comment]
@alextrastero After looking into this more today, I see why sizes were allowed in the Input specifications and why, although it's "more work," it makes sense to do what was initially implemented. Right now, you end up with an unnecessary extra <div>, as far as I can tell, since it would render like so:

```
<div class="col s12">
    <div class="input-field">
        <i class="material-icons prefix">account_circle</i>
        <input id="icon_prefix" type="text" class="validate">
        <label for="icon_prefix">First Name</label>
    </div>
</div>
```
instead of the more efficient and familiar specification in the vanilla MaterializeCSS
```
<div class="input-field col s12">
    <i class="material-icons prefix">account_circle</i>
    <input id="icon_prefix" type="text" class="validate">
    <label for="icon_prefix">First Name</label>
</div>
```

Consider this from the current Input.js:
```
<div className={cx(classes)}>
    { this.renderIcon() }
    {htmlLabel}
    <select
        {...other}
        multiple={multiple}
        id={this._id}
        className={cx(className, inputClasses)}
        ref={(ref) => (this.selectInput = ref)}
        defaultValue={defaultValue}
    >
        { options }
    </select>
</div>
```

If we remove the wrapping <div>, then this is no longer a component since adjacent elements have to have a wrapping parent element to be a component. It becomes clear that due to the requirement of a wrapping parent element, we must add sizing props directly to this particular component

```
<Input s={12} m={8} l={6} offset="m2 l3" />
```
instead of the arguably more familiar-looking (at least, to users of vanilla MaterializeCSS)
```
<Col  s={12} m={8} l={6} offset="m2 l3">
    <Input />
</Col>
```
to avoid the redundant <div> that I mentioned earlier. 

If the redundant <div> doesn't matter in the interest of consistency, then that's what we can do. After skimming the vanilla MaterializeCSS (0.100.2) documentation, not all components would need sizing props. The form fields are a special case because they have labels and icons adjacent.

**Comment by alextrastero** [comment]
I still think that layout components should be separate from the rest. If I want a component to occupy X amount of space I wouldn't mind adding a layout component as a wrapper
