### ISSUE TITLE
Add Autocomplete to DOCS

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#243]
Autocomplete component was added sometime ago but there's no example on the DOCS, now that the docs are new, they're easy to setup and maintain, would be great if someone could have a look at this. :)

**Comment by hermano360** [comment]
Hey!
Started working on getting Autocorrect up and running and looking at the source code to discern the functionality. I'll give it a shot with regards to the example. One question, in the regular Materialize documentation, it has an onAutocomplete option. When trying to implement that functionality, I saw that the onChange property on the Autocomplete constantly changing the state, rather than only when the dropdown menu item is clicked. In the renderDropdown function, the result returned is:

 `              <li key={key + '_' + idx} onClick={(evt) => this.setState({ value: key })}>
                {data[key] ? <img src={data[key]} className='right circle' /> : null}
                <span>
                  {index !== 0 ? key.substring(0, index) : ''}
                  <span className='highlight'>{value}</span>
                  {key.length !== index + value.length ? key.substring(index + value.length) : ''}
                </span>
              </li>
`

But the component itself is also updating the state:

`_onChange (evt) {
    this.setState({ value: evt.target.value });
  }
`

 making it difficult to discern whether a change or a click is the reason for the updated state. The work around I had was just to constantly check whether the state matched one of the data object keys. Do you have any suggestions on an alternative solution?

**Comment by alextrastero** [comment]
https://github.com/react-materialize/react-materialize/pull/369
