### ISSUE TITLE
Docs unknown props warnings

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#322]
Currently there's a warning in the docs:
`Unknown props `expanded`, `eventKey` on <li> tag`, should be happening somewhere in `Navigation.js`.

**Comment by jawadsh123** [comment]
I went through the code and I believe this error might be happening because of the way the Collapsible component is built.
Every child of Collapsible gets the "expanded", "eventKey" and "onSelect" props.
When all of the children are "CollapsibleItem" components, there is no problem, since, "CollapsibleItem" accepts all the above props.
But in case of the docs, we have an additional <li> being rendered as a child of the main "Collapsible" component. Since <li> can only accept "onSelect" from the above props, we get the error.

I haven't tested any of the above though. I'll try to test it and get back to you. Maybe we'll need to change the core Collapsible file to only add those props to the "CollapsibleItem" children.

**Comment by jawadsh123** [comment]
My assumption was correct.
The problem is arising when the children of Collapsible are not CollapsibleItem but regular dom elemets.
Since there might be cases where we might want to include regular tags inside Collapsible, I've modified it to accomodate those. Now there shouldn't be any error in the console.

**Comment by isaiah** [comment]
@alextrastero could you take a look?

**Comment by alextrastero** [comment]
Review added :)

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
