### ISSUE TITLE
Unable to change the NavItem text color

### ISSUE THREAD

**Issue by azmathtech** [react-materialize/react-materialize#326]
I am able to change the color of the Navbar but am not able to change the text color of the NavItem.  

<NavItem className="blue-text">Link</NavItem> - this does not change the color
<NavItem className="blue">Link</NavItem> - this changes the background color of the nav bar to blue just behind the link.

How can the text color be changed?

**Comment by azmathtech** [comment]
Update - I was finally able to change the text color but I had to wrap the text in a div within the Navitem and then apply the className to the div.  

Any idea why a classname="color-text" does not work on the NavItem?

**Comment by alextrastero** [comment]
Hey @azmathtech, as you can see here:
https://github.com/react-materialize/react-materialize/blob/master/src/NavItem.js#L12
The rest of props are passed to `li` but not to `a`, maybe we should be able to pass a prop Node that would be the link instead of an `a`, that what you could pass a custom Node with that className already applied

**Comment by alextrastero** [comment]
Check out the linked PR to see if that would solve the issue :)

**Comment by azmathtech** [comment]
Thank you for the quick reply.  That makes sense.  Looking back at the code for both the Navbar and NavItem I understand why its working the way it does.
