### ISSUE TITLE
Javascript components are not working 

### ISSUE THREAD

**Issue by harishrohokale** [react-materialize/react-materialize#339]
Hi All
Can someone please help me with this issue?
bundle.js:137057 Uncaught TypeError: $(...).dropdown is not a function
at Dropdown.componentDidMount (bundle.js:137057)
at bundle.js:127288
at measureLifeCyclePerf (bundle.js:127098)
at bundle.js:127287
at CallbackQueue.notifyAll (bundle.js:54095)
at ReactReconcileTransaction.close (bundle.js:132181)
at ReactReconcileTransaction.closeAll (bundle.js:28008)
at ReactReconcileTransaction.perform (bundle.js:27955)
at ReactUpdatesFlushTransaction.perform (bundle.js:27942)
at ReactUpdatesFlushTransaction.perform (bundle.js:19908)
I have added js dropdown component in my react app
I am stuck with this
please do share your thoughts on it

I tried with most of the JS components but it returns the same error.

**Comment by alextrastero** [comment]
Are you using create-react-app?

**Comment by harishrohokale** [comment]
@alextrastero I am using https://github.com/react-materialize/react-materialize this only
I have referred the document https://react-materialize.github.io/#/

**Comment by alextrastero** [comment]
@harishrohokale I see, but where are you using `react-materialize` on you're own Webpack? or on some other boilerplate like `create-react-app` ?

**Comment by harishrohokale** [comment]
@alextrastero I am using my own webpack but i have followed the steps to add dependencies as per the document

**Comment by alextrastero** [comment]
I see, can you paste here your index.html?

**Comment by harishrohokale** [comment]
@alextrastero 
```
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en">
    <head>
      <title>React Demo App</title>
      <meta charset="utf-8">
      <!-- Use minimum-scale=1 to enable GPU rasterization -->
      <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0, maximum-scale=1, minimum-scale=1">
      <link rel="shortcut icon" href="app/assets/fonts/fivicon.png">
      <script src="ftp://bgbilling.ru/pub/bgbilling/activemq/win/apache-activemq-5.4.2/webapps/demo/js/amq_jquery_adapter.js"></script>
      <script src="https://svn.apache.org/repos/asf/activemq/trunk/activemq-web-demo/src/main/webapp/js/amq.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/stomp.js/2.3.3/stomp.js"></script>

      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      <!-- Import Google Icon Font -->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!-- Import materialize.css -->
      <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css" rel="stylesheet">

    </head>
    <body>
        <div id="app"></div>

        <!-- Import jQuery before materialize.js -->
        	<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
    </body>
</html>
```

**Comment by alextrastero** [comment]
But how are you bundling you're react code? where is the `<script src="bundle.js"></script>`?

**Comment by harishrohokale** [comment]
Adding bundle.js during run time by using webpack.
See attached screenshots
![screen shot 2017-08-23 at 10 22 21 pm](https://user-images.githubusercontent.com/6389000/29628007-bb9a6856-8851-11e7-8bac-b5fb0fee657d.png)

![screen shot 2017-08-23 at 10 22 40 pm](https://user-images.githubusercontent.com/6389000/29628004-b80f814e-8851-11e7-95ea-1f2e8232326e.png)

**Comment by harishrohokale** [comment]
@alextrastero Any updates?

**Comment by alextrastero** [comment]
Have you tried other JavaScript components? Like Modal?

On Aug 23, 2017 20:27, "Harish Rohokale" <notifications@github.com> wrote:

@alextrastero <https://github.com/alextrastero> Any updates?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/react-materialize/react-materialize/issues/339#issuecomment-324421893>,
or mute the thread

**Comment by harishrohokale** [comment]
@alextrastero Tried with other JS components too. Same issue for other

**Comment by alextrastero** [comment]
Hi @harishrohokale, just tried again with the latest version, works fine for me. You might have some issue in your webpack configuration, the docs are updated with the latest version and it also works: https://react-materialize.github.io/#/dropdown.

Some users have had issues when using create-react-app because of the order in which the scripts are added to the index.html.

What are you using to add bundle.js during runtime? `HtmlWebpackPlugin`?

**Comment by alextrastero** [comment]
Also, you might find the answer here: https://github.com/Dogfalo/materialize/issues/1229#issuecomment-242417847

**Comment by harishrohokale** [comment]
@alextrastero I am using HtmlWebpackPlugin
I tried with the solution which is given in  Dogfalo/materialize#1229 (comment) i.e.
```
alias: {
      'jquery': path.join( __dirname, 'node_modules/jquery/dist/jquery' ),
    }
plugins: [
      new webpack.ProvidePlugin({
          $: 'jquery',
          jQuery: "jquery",
          'window.$': 'jquery',
          'window.jQuery': 'jquery',
      })
  ]
and 
module: {
  loaders: [
      {
          test: '/materialize-css/bin/',
          loader: 'imports?jQuery=jquery,$=jquery,hammerjs'
      }
  }

but no luck :(

**Comment by harishrohokale** [comment]
@alextrastero Can you provide me working seed project with webpack?

**Comment by harishrohokale** [comment]
@alextrastero Any updates?

**Comment by alextrastero** [comment]
Hi @harishrohokale, this issue is not a `react-materialize` issue. It seems you need to add some extra configuration to your webpack config.
As for seed project, if you clone https://github.com/alextrastero/react-webpack-boilerplate and run `npm i && npm i -S react-materialize` this works.

#330 was solved with some fix from Aguego here https://github.com/Dogfalo/materialize/issues/1229

Good luck!
