### ISSUE TITLE
Tabs are not working properly

### ISSUE THREAD

**Issue by harishrohokale** [react-materialize/react-materialize#392]
Tabs are not working properly when this.setState({field1: this.field1}) executes. If i comment this.setState code then it works as expected. Can you please help me to fix this?

**Comment by alextrastero** [comment]
Hey @harishrohokale could please paste a code example of what's not working and the expected behaviour?

**Comment by harishrohokale** [comment]
@alextrastero Basically I have used the Tabs such as below in the same JSX file where i have the API calls to get the data from backend. Once i receive the data from backend i do this.setState({}) with some fields. Which basically change the state on ui and reinitiate the UI. I think thats causing the issue. When i do comment the API calls everything works fine.

So the issue is when i do setState.

**Comment by alextrastero** [comment]
So when Tabs receives new props, it stops working?

**Comment by dmitry-yudakov** [comment]
In Tabs render() there's **scope** variable used later in **<li key={}>**. It's regenerated on every render, which will rebuild <ul> contents every time because of their changed keys.

Meanwhile **$(...).tabs()** is only called once in componentDidMount.

Could the **scope** variable be generated in constructor and then preserved for the instance's lifetime? It could fix the issue with the tabs and optimize the general performance because the child elements won't be remounted every time.

@harishrohokale as a quick workaround you could force remounting of the whole Tabs element by passing it unique 'key' property every time, something like **key={'tabs'+Date.now()}**

**Comment by harishrohokale** [comment]
@dmitry-yudakov Worked Thanks!

**Comment by yashank09** [comment]
Hey guys, Im kinnda having the same problem and have been struggling for two days now :/ Im using Tabs to get inputs from user and sending them on button click to my state. However I can properly get the first input, but the moment I type on the second input of the first tab, both the tabs gets merged for some reason and become unresponsive.. Any workaround? Im sorry I couldnt really understand @dmitry-yudakov solution :/

**Comment by dmitry-yudakov** [comment]
@yashank09 The workaround I mentioned is basically forcing react to unmount and then create and mount Tabs component every time.

```
<Tabs 
  key={'tabs' + Date.now()} 
  onChange={onChange}
>
```
Note the _key_ property in the sample - its unique value is what forces the Tabs component to be recreated every time.

I may try to fix this issue permanently, perhaps along with 3.0.0-beta.0 in #607
