### ISSUE TITLE
sideNav unexpected show-on-large

### ISSUE THREAD

**Issue by mnax001** [react-materialize/react-materialize#531]
### Description

I don't know why is the library adding a show-on-large css rule for the trigger component. I checked the code and it is setting a class show-on-large if the prop `fixed` is false. I don't know....I think that the show rule should not be set. 

### Steps to Reproduce
Create a sideNav with a trigger component who has a `hide-on-med-and-up` className
```
<SideNav
    trigger={
      <a href="#" className="button-collapse hide-on-med-and-up">
             <i className="material-icons">menu</i>
       </a>
      }
>
         <SideNavItem href='/' waves icon='home'>INICIO</SideNavItem>      	
 </SideNav>
```
**Expected behavior:** 
the button to be hidden on medium and up

**Actual behavior:** [What actually happens]
still there in medium and up 😞 
### Versions

**react-materialize:** 2.2.0
**materialize-css:**  0.100.2
**react:** 16.3.2

**Comment by Xstoudi** [comment]
Up!

**Comment by Xstoudi** [comment]
Up! @alextrastero that's not excpected.

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!

**Comment by mkaniaa** [comment]
My versions:
**react-materialize:** 3.8.3
**materialize-css:** 1.0.0
**react:** 16.13.1

### Description
The same problem in my case. Library still adds "show-on-large" class for the sidenav's trigger component, when the prop fixed is false. It blocks the possibility to hide the trigger button on a large screen.

### Steps to Reproduce
1. Create the SideNav component, passing the button with class "hide-on-large-only" to the trigger option:

        <SideNav
            options={{preventScrolling: true}}
            trigger={
                <Button 
                    className="hide-on-large-only"
                    icon={<Icon>menu</Icon>}
                >
                </Button>
            }
        >
            <SideNavItem>
                <p>item</p>
            </SideNavItem>
        </SideNav>

**Expected behavior:** [What you expect to happen]
Trigger component (button) should be visible only on med and small screens.

**Actual behavior:** [What actually happens]
Trigger component (button) is always visible (also on large sceens) because it gets an additional automaticly added class "show-on-large" which covers the "hide-on-large-only" class and prevent hiding the button on large screens.
