### ISSUE TITLE
3.0.0 Tabs.js & Tab.js

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#607]
### Upgrade to latest materialize-css@1.0.0-rc.2

AC
- Branch off 3.0.0-beta.0
- Check that the component works
- Keep jQuery initialisation of component if exists
- Update with new available modifiers and options
- Update propTypes and description
- Update examples page
- Create PR into branch 3.0.0-beta.0

**Comment by dmitry-yudakov** [comment]
I'd like to help with this

**Comment by alextrastero** [comment]
Woohoo, yes :)

**Comment by alextrastero** [comment]
Let me know if I can support you in anything

**Comment by alextrastero** [comment]
Have a look at https://github.com/react-materialize/react-materialize/pull/613 if you need to

**Comment by dmitry-yudakov** [comment]
#613 helped a lot, thanks :)

I think this issue is resolved and covered by tests update.

#408, #392 is fixed as well and manually tested but I think I can't cover it with enzyme test. Any advice for this?

I tried adding `expect(wrapper.find('#tab_10')).toHaveLength(1);` after _shallow/mount_ but it finds either 0 or 2 elements...

**Comment by dmitry-yudakov** [comment]
Well, I was wondering if I should cover Tabs lifecycle refactoring by some test - so I tried to modify _Tabs.spec.js_ to check that elements ids are not changed anymore after re-render or properties update.

**Comment by alextrastero** [comment]
You could add a spy to `idgen` and count how many times it was called?

**Comment by dmitry-yudakov** [comment]
Yes, it worked, thanks

**Comment by alextrastero** [comment]
Thanks for this @dmitry-yudakov
