### ISSUE TITLE
JS components not initially rendered don't work

### ISSUE THREAD

**Issue by rulatir** [react-materialize/react-materialize#74]
Javascript components like Dropdown don't work if they are not rendered initially but only subsequently upon an ancestor's state change.

Attached is a diff against boilerplate commit 2fe4b89847a57459804d8078e8ffd98158492042 that demonstrates the issue. You need to change the initial `ready` state value from `true` to `false` to see the symptom.

[demonstrate-delayed-render-bug.txt](https://github.com/react-materialize/react-materialize/files/300235/demonstrate-delayed-render-bug.txt)

This is probably the real issue behind #70 .

**Comment by sminutoli** [comment]
Dropdown isn't working yet, I'm using 0.14.5 because 0.14.6 throws errors...

**Comment by alextrastero** [comment]
hey @sminutoli, what kind of errors are you seeing?

**Comment by sminutoli** [comment]
Hi @alextrastero I'm getting a `jquery.js:4311 Uncaught TypeError: Cannot read property 'createDocumentFragment' of undefined`. 
After some debugging I've found that `this._trigger` is a ReactElement instead a DOM Element in the `componentDidMount` hook. 
If I apply `$('.dropdown-button').dropdown()` instead of `$(this._trigger).dropdown()` it seems to work well (tough isn't the right solution).
I'm having this issue mounting the dropdown _after_ a re-render of a previous screen/route.

**Comment by sminutoli** [comment]
@alextrastero do you have a clue about this one?

**Comment by sminutoli** [comment]
I've made a PR with a proposal https://github.com/react-materialize/react-materialize/pull/110

**Comment by alextrastero** [comment]
please reopen if this is not fixed :)
