### ISSUE TITLE
BETA: Dropdown init not working

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#749]
In 3.0.0-beta branch the dropdown is not working, for some reason calling init with a ref doesn't work but with a node selector it does:

```jsx
var elems = document.querySelectorAll('.dropdown-trigger');
this.instance = M.Dropdown.init(elems, options); //works

// ref: t => (this._trigger = `[data-target=${this.idx}]`),
this.instance = M.Dropdown.init(this._trigger, options); //doesnt work
```

Ideally like other components we wouldn't need to rely on a classname. `materialize-css` dropdown.js needs to be inspected to see why it doesn't work.

**Comment by onluiz** [comment]
It looks like `this._trigger` has only the string `[data-target=${this.idx}] ` instead of an actual element.

I tried to change `ref: t => (this._trigger = ``[data-target=${this.idx}]``)` to ``ref: t => (this._trigger = t)` and no success too.

It only worked when I tried getting my ref manually from target button, like this:

`ref: t => (this._trigger = t._btnEl)`

But I assume that dropdown is probably not going to be used only with our Button component as target. Is there any other way to get elements ref considering our case?
