### ISSUE TITLE
Codesandbox

### ISSUE THREAD

**Issue by MilePaor** [react-materialize/react-materialize#762]
### Description

react-materialize package does not work with react hooks inside codesandbox editor.

### Versions

**react-materialize:** 2.6.0
**materialize-css:** 0.98.0
**react:** 16.8.2

#### Thanks for helping out!
![materialize](https://user-images.githubusercontent.com/20985604/52881282-7622e600-3164-11e9-836b-b8a99a581032.jpg)

**Comment by onluiz** [comment]
Can you post a link for your CodeSandbox example?

**Comment by onluiz** [comment]
Steps to reproduce:
- Create a new CodeSandbox
- Add useState function (as described into @MilePaor print above)
You will observe that everything works fine.

Then add react-materialize dependence and the box stop working (above error).

@MilePaor, the same problem happens when you use create-react-app on your machine? It would be nice to know in case that only occurs on CodeSandbox.

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
