### ISSUE TITLE
Button component - docs unclear/wrong

### ISSUE THREAD

**Issue by EuniceB** [react-materialize/react-materialize#846]
### Description

I wanted to add a floating button on the bottom right corner of the page, so I checked the documentation and it says that the fab option takes an object like this:
```
{
   direction?: oneOf 'top' | 'right' | 'bottom' | 'left',
   hoverEnabled?: bool,
   toolbarEnabled?: bool
}
```
so I tried to add this to my code:
```
<Button
      floating
      large
      className="yellow"
      waves="light"
      icon="add"
      fab={
            direction: "bottom"
      }
/>
```
but the compiler says it's not valid:

> Syntax error: Unexpected token, expected "}" (16:25)

I checked other people's examples and found out that it should actually be like this:
```
<Button
          floating
          large
          className="yellow"
          waves="light"
          icon="add"
          fab="vertical"
        />
```
which has nothing to do with what is on the docs.

### Versions

**react-materialize:** 3.1.1
**materialize-css:** 1.0.0
**react:** 16.8.6

**Comment by EuniceB** [comment]
Also, I noticed that using the fab option gets me this error on the console:

> index.js:1437 Warning: Failed prop type: Invalid prop `fab` supplied to `Button`.

**Comment by CloudPower97** [comment]
@EuniceB Other people's examples are coming from version 2.5.0 and backwards.
From version 3.x.x the correct `prop` for `Button` is a `boolean` or an `object` with this shape:
```javascript
{
      direction: PropTypes.oneOf(['top', 'right', 'bottom', 'left']),
      hoverEnabled: PropTypes.bool,
      toolbarEnabled: PropTypes.bool
}
```

This `Syntax error: Unexpected token, expected "}" (16:25)` is because you have to enclose the `object` in another pairs of curly brackets:

```javascript
<Button
      floating
      large
      className="yellow"
      waves="light"
      icon="add"
      fab={{
            direction: "bottom"
      }}
/>
```

I've created a box, you can experiment with it here.

[![Edit q7k8wz304w](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q7k8wz304w?fontsize=14)

**Comment by EuniceB** [comment]
Thank you for your help :)
